Updates logger script reference in git scripts

diff --git a/scripts/git/hooks/post-update b/scripts/git/hooks/post-update
--- a/scripts/git/hooks/post-update
+++ b/scripts/git/hooks/post-update
@@ -1,13 +1,16 @@
-#!/bin/sh
+#!/bin/bash
 #
 # An example hook script to prepare a packed repository for use over
 # dumb transports.
 #
 # To enable this hook, rename this file to "post-update".
 
+# Cause the script to exit immediately if a command returns a non-zero exit status (indicating an error)
+set -e
+
 git_dir=$(git rev-parse --show-toplevel)
 cd $git_dir 1>post-update.log
-source $(pwd)/tools/scripts/utils/logger.sh
+source $(pwd)/tools/scripts/git/utils/logger.sh
 cd - 1> post-update.log
 rm post-update.log
 
diff --git a/scripts/git/hooks/update b/scripts/git/hooks/update
--- a/scripts/git/hooks/update
+++ b/scripts/git/hooks/update
@@ -1,12 +1,15 @@
-#!/bin/sh
+#!/bin/bash
+
+# Cause the script to exit immediately if a command returns a non-zero exit status (indicating an error)
+set -e
 
 # =============================================================================
 # Fun Fact: we can use the following shebang line for cross-compiling:
-# /* #!/bin/sh; C:/Program\ Files/path/to/Git/usr/bin/sh.exe */
+# /* #!/bin/bash; C:/Program\ Files/path/to/Git/usr/bin/sh.exe */
 # according to https://www.youtube.com/watch?v=fMYv6-SZsSo
 # =============================================================================
 
-source $(pwd)/tools/scripts/utils/logger.sh
+source $(pwd)/tools/scripts/git/utils/logger.sh
 
 log_info "Running update hook..."
 
