Updates git hooks

diff --git a/scripts/git/hooks/pre-commit b/scripts/git/hooks/pre-commit
--- a/scripts/git/hooks/pre-commit
+++ b/scripts/git/hooks/pre-commit
@@ -10,11 +10,26 @@
 # Script setup
 # ============================================================================
 
-# navigate to project root directory
-git_dir=$(git rev-parse --show-toplevel)
-cd $git_dir 1>pre-commit.log
-# add logger to the scope
-source $(pwd)/tools/scripts/git/utils/logger.sh
+# get the directory where the script is located
+THIS_SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
+
+# import git utilities
+GIT_UTILITIES_SCRIPT_PATH=$THIS_SCRIPT_DIR/../git/utils/utilities.sh
+test -f $GIT_UTILITIES_SCRIPT_PATH || (echo "File not found: $GIT_UTILITIES_SCRIPT_PATH" && exit 1)
+source $GIT_UTILITIES_SCRIPT_PATH || (echo "Failed to source $GIT_UTILITIES_SCRIPT_PATH" && exit 1)
+
+# detect if this tools folder is a submodule or not
+IS_SUBMODULE=$(git_is_submodule; echo $?)
+
+# getting the root level directory of the project
+PROJECT_ROOT_DIR=$(git rev-parse --show-toplevel)
+if [[ $IS_SUBMODULE == 1 ]]; then
+    cd "${PROJECT_ROOT_DIR}/.."
+    PROJECT_ROOT_DIR=$(git rev-parse --show-toplevel)
+fi
+
+# import logger
+source ${PROJECT_ROOT_DIR}/tools/scripts/utils/logger.sh
 
 CMAKE_CURRENT_LOG_LEVEL=$CMAKE_LOG_LEVEL_TRACE
 
